
```{r}

library(tidyverse)
library(plotly)
library(lubridate)

```

Load in required files

```{r}

SVI = read.csv("G:\\My Drive\\School\\CDC\\CDC2021\\datasets\\Social Science\\SVI_County.csv")
covid_deaths = read.csv("G:\\My Drive\\School\\CDC\\CDC2021\\datasets\\Social Science\\covid_deaths_usafacts.csv")

```


Posture covid deaths 

```{r}

covid_deaths_tall = gather(covid_deaths, date, deaths, colnames(covid_deaths)[5]:colnames(covid_deaths)[length(colnames(covid_deaths))], factor_key=F)

covid_deaths_tall$date = ymd(str_remove_all(substr(covid_deaths_tall$date, 2, nchar(covid_deaths_tall$date)),"\\."))

```

Filter Covid deaths for just the last day

```{r}

covid_deaths_tall_mostrecent = subset(covid_deaths_tall, date == '2021-09-26')

```

Inner join Covid and SVI datasets

```{r}

SVI_COVID_Deaths = merge(SVI, covid_deaths_tall_mostrecent, by.x = "STCNTY", by.y = "countyFIPS")

variables_of_interest = c("CEPL_POV", "CEPL_UNEMP", "CEPL_PCI", "CEPL_NOHSDP", "CEPL_PCI", "CEPL_AGE65", "CEPL_POV","CEPL_UNEMP", "CEPL_PCI", "CEPL_NOHSDP", "CEPL_AGE65", "CEPL_AGE17", "CEPL_DISABL", "CEPL_SNGPNT", "CEPL_MUNIT", "CEPL_MOBILE", "CEPL_CROWD", "CEPL_NOVEH", "CEPL_GROUPQ")

SVI_COVID_Deaths_new = SVI_COVID_Deaths[,variables_of_interest]

```

