## Posturing covid deaths, infection and vaccination data for joining with SVI dataset


# Load in the required libraries

```{r}

library(tidyverse)
library(lubridate)

```

# Load in required files

```{r}
covid_deaths = read.csv("../datasets/Social Science/covid_deaths_usafacts.csv")
covid_vaccine = read.csv("../datasets/Social Science/covid_deaths_usafacts.csv")
covid_infection = read.csv("../datasets/Social Science/covid_confirmed_usafacts.csv")
```

# Create tall dataframes

```{r}
covid_deaths_tall = gather(covid_deaths, date, deaths, colnames(covid_deaths)[5]:colnames(covid_deaths)[length(colnames(covid_deaths))], factor_key=F)
covid_vaccine_tall = gather(covid_vaccine, date, total_vaccines, colnames(covid_vaccine)[5]:colnames(covid_vaccine)[length(colnames(covid_vaccine))], factor_key=F)
covid_infection_tall = gather(covid_infection, date, total_infection, colnames(covid_infection)[5]:colnames(covid_infection)[length(colnames(covid_infection))], factor_key=F)
```

# Remove the "X" that appears at the beginning of every date and convert it into a date object

```{r}
covid_deaths_tall$date = ymd(substring(covid_deaths_tall$date, 2))
covid_vaccine_tall$date = ymd(substring(covid_vaccine_tall$date, 2))
covid_infection_tall$date = ymd(substring(covid_infection_tall$date, 2))
```

# Create the final table

```{r}
new_tall = covid_infection_tall %>%
            filter(countyFIPS != 0) %>% 
            inner_join(covid_vaccine_tall, by = c("countyFIPS", "date"), suffix = c(".inf", ".vac")) %>% 
            inner_join(covid_deaths_tall, by = c("countyFIPS", "date"), suffix = c(".vac", ".det"))

final = new_tall %>%
          select(countyFIPS,
                 date,
                 total_infection,
                 total_vaccines,
                 deaths) %>% 
          gather(type, value, total_infection:deaths)
```

# Write the file

```{r}
write.csv(final, "../datasets/Social Science/COVID_postured.csv")
```



