## Posturing covid deaths, infection and vaccination data for joining with SVI dataset


Load in the required libraries

```{r}

library(tidyverse)
library(lubridate)

```

Load in required files

```{r}

covid_deaths = read.csv("C:\\Users\\taywo\\Documents\\Git Repos\\CDC2021\\datasets\\Social Science\\covid_deaths_usafacts.csv")
covid_vaccine = read.csv("C:\\Users\\taywo\\Documents\\Git Repos\\CDC2021\\datasets\\Social Science\\covid_deaths_usafacts.csv")
covid_infection = read.csv("C:\\Users\\taywo\\Documents\\Git Repos\\CDC2021\\datasets\\Social Science\\covid_confirmed_usafacts.csv")

```

Convert county names so that they match up with SVI dataset

```{r}

# change_county_name = function(county_name){
#   new_county_name = ifelse(str_detect(county_name, "County") == TRUE || str_detect(county_name, "county") == TRUE, substr(county_name, 1, nchar(county_name)-7), county_name)
#   return(new_county_name)
# }
# 
# change_county_name = Vectorize(change_county_name)
# 
# covid_deaths$County.Name = change_count_name(covid_deaths$County.Name)
# covid_infection$County.Name = change_count_name(covid_infection$County.Name)
# covid_vaccine$County.Name = change_count_name(covid_vaccine$County.Name)

```

Create tall dataframes

```{r}

covid_deaths_tall = gather(covid_deaths, date, deaths, colnames(covid_deaths)[5]:colnames(covid_deaths)[length(colnames(covid_deaths))], factor_key=F)
covid_vaccine_tall = gather(covid_vaccine, date, total_vaccines, colnames(covid_vaccine)[5]:colnames(covid_vaccine)[length(colnames(covid_vaccine))], factor_key=F)
covid_infection_tall = gather(covid_infection, date, total_infection, colnames(covid_infection)[5]:colnames(covid_infection)[length(colnames(covid_infection))], factor_key=F)

covid_deaths_tall
```

Remove the "X" that appears at the beginning of every date and convert it into a date object

```{r}

covid_deaths_tall$date = ymd(substring(covid_deaths_tall$date, 2))
covid_vaccine_tall$date = ymd(substring(covid_vaccine_tall$date, 2))
covid_infection_tall$date = ymd(substring(covid_infection_tall$date, 2))

```

```{r}
covid_vaccine_tall = read.csv("C:\\Users\\taywo\\Documents\\Git Repos\\CDC2021\\datasets\\Social Science\\vaccine_data_by_county.csv")
covid_vaccine_tall$date = mdy(covid_vaccine_tall$Date)
covid_vaccine_tall$countyFIPS = as.numeric(covid_vaccine_tall$FIPS)
covid_vaccine_tall$total_vaccines = covid_vaccine_tall$Administered_Dose1_Recip
```

```{r}

new_tall = covid_infection_tall %>%
            filter(countyFIPS != 0) %>% 
            inner_join(covid_vaccine_tall, by = c("countyFIPS", "date"), suffix = c(".inf", ".vac")) %>% 
            inner_join(covid_deaths_tall, by = c("countyFIPS", "date"), suffix = c(".vac", ".det"))

final = new_tall %>%
          select(countyFIPS,
                 date,
                 total_infection,
                 total_vaccines,
                 deaths) %>% 
          gather(type, value, total_infection:deaths)

final %>%
  filter(type == "total_vaccines",
         date > "2020-07-01")
```

```{r}
write.csv(final, "C:\\Users\\taywo\\Documents\\Git Repos\\CDC2021\\datasets\\Social Science\\COVID_postured.csv")
```



